- hosts: localhost
  gather_facts: yes
  vars_files:
    - keys.yml
  tasks:
    - name: create a new instaces
      ec2_vpc_net_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
           "tag:Name": NewVpc
      register: vpc_facts
    - debug:
        var: vpc_facts
    - name: adding the vpc cidr rang
      shell: aws ec2 associate-vpc-cidr-block --vpc-id "{{ vpc_facts.vpcs[0].vpc_id }}" --cidr-block 10.3.0.0/24 
